ekan_core.resource_settings:
  type: config_object
  label: 'Resource Settings'
  mapping:
    upload:
      type: mapping
      label: 'Upload'
      mapping:
        uri_scheme:
          type: string
          label: 'URI Scheme'
        file_directory:
          type: string
          label: 'File directory'
        file_extensions:
          type: string
          label: 'Allowed file extensions'
        max_filesize:
          type: string
          label: 'Maximum upload size'
